# Secrets can be stored in .secrets.toml and referenced using {token} syntax 
# as per the authorization header token below
# optionally create a .secrets.toml file (see .secrets.example.toml) and add your secrets there
# The .secrets.toml file should not be committed to version control


# strategy = "polling" ==> the data will be fetched once, at server start-up
# strategy = "webhook" ==> POST new data to /webhook
strategy = "polling"

# Poll URL (required for polling strategy)
url = "https://example.com/data.json"

# Automatically re-render the view when Liquid templates change (default: true)
live_render = true

# Polling headers (optional, for polling strategy)
[polling_headers]
authorization = "{authorization}"
content-type = "application/json"
